"""notifications

Revision ID: d76d1076f1f6
Revises: e51ac549e199
Create Date: 2017-12-23 11:55:32.007025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76d1076f1f6'
down_revision = 'e51ac549e199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('payload_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'payload_json')
    # ### end Alembic commands ###
